name: Verify Packages

on:
  pull_request:
    paths:
      - src/**

permissions:
  contents: read

jobs:
  verify:
    name: Verify Packages
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify subtree-splits are auto-closed
        run: |
          php .github/sync-packages.php
          git add src/
          git diff --staged --exit-code || (echo '::error::Please run "php .github/sync-packages.php".' && exit 1)
